import { error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { readFileSync, existsSync, readdirSync, statSync } from 'fs';
import { resolve } from 'path';

export const GET: RequestHandler = async () => {
    const tilesDir = resolve('..', 'output', 'tiles');
    const metadataPath = resolve(tilesDir, 'metadata.json');
    
    // 1. Try to return existing metadata.json
    if (existsSync(metadataPath)) {
        try {
            const metadata = readFileSync(metadataPath, 'utf-8');
            return new Response(metadata, {
                headers: { 'Content-Type': 'application/json' }
            });
        } catch (e) {
            console.error("Error reading metadata.json:", e);
        }
    }
    
    // 2. Fallback: Generate metadata from directory structure
    if (!existsSync(tilesDir)) {
        throw error(404, 'Tiles directory not found');
    }
    
    try {
        const items = readdirSync(tilesDir);
        const dates = items
            .filter(item => /^\d{4}-\d{2}-\d{2}$/.test(item))
            .filter(item => {
                try {
                    return statSync(resolve(tilesDir, item)).isDirectory();
                } catch {
                    return false;
                }
            })
            .sort();

        if (dates.length === 0) {
            throw error(404, 'No tile date folders found (YYYY-MM-DD)');
        }

        const metadata = {
            dates,
            center: [33.8824, -83.4351], // Default coordinates
            default_zoom: 15,
            generated: true,
            info: "Automatically generated by proxy because metadata.json was missing"
        };

        return new Response(JSON.stringify(metadata, null, 2), {
            headers: {
                'Content-Type': 'application/json'
            }
        });
    } catch (e) {
        console.error("Error auto-generating metadata:", e);
        throw error(500, 'Internal server error during metadata generation');
    }
};
